// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const addHighlight: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').addHighlight
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const generateId: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').generateId
  const getAllHighlights: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').getAllHighlights
  const getElementByXPath: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/xpath').getElementByXPath
  const getStorageKey: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').getStorageKey
  const getXPath: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/xpath').getXPath
  const injectModalStyles: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/modal').injectModalStyles
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const loadHighlights: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').loadHighlights
  const normalizeUrl: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').normalizeUrl
  const removeHighlight: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').removeHighlight
  const removeModal: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/modal').removeModal
  const saveHighlights: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/storage').saveHighlights
  const showHighlightModal: typeof import('/Users/hzhou/GitHub/chrome-highlighter/utils/modal').showHighlightModal
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { HighlightMetadata } from '/Users/hzhou/GitHub/chrome-highlighter/utils/modal'
  import('/Users/hzhou/GitHub/chrome-highlighter/utils/modal')
  // @ts-ignore
  export type { HighlightColor, HighlightPosition, PageHighlights } from '/Users/hzhou/GitHub/chrome-highlighter/utils/types'
  import('/Users/hzhou/GitHub/chrome-highlighter/utils/types')
}
